export const emptyGetStateResult = {
  blur: false,
  error: null,
  focus: false,
  id: null,
  invalid: {},
  meta: null,
  savedValue: null,
  saving: false,
  valid: {},
  value: null,
  editing: false,
  dirty: false,
  errorMessage: null,
  hasError: false,
  initialValue: null,
  open: false,
  pristine: true,
  saved: false,
  status: null,
  suggestion: null,
  isValid: false,
}
